# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Freida Blostein - PhD Candidate Epidemiology University of Michigan
email: blostein@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  "I'm a PhD candidate in Epidemiologic Science at the University of Michigan. My work broadly uses high-dimensional omics measurements as markers and mediators of enivronment-disease relationships. I also love science fiction, poetry & dogs." 
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.freidablostein.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: freidablostein
github_username:  blostein

header_pages: 
  - about.md
  - Research/index.md
  - Teaching/index.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
